In [1]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] 

FileNotFoundError: [Errno 2] No such file or directory: 'mpg.csv'

In [2]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] 

[OrderedDict([('street', '3526 HIGH ST'),
              ('city', 'SACRAMENTO'),
              ('zip', '95838'),
              ('state', 'CA'),
              ('beds', '2'),
              ('baths', '1'),
              ('sq__ft', '836'),
              ('type', 'Residential'),
              ('sale_date', 'Wed May 21 00:00:00 EDT 2008'),
              ('price', '59222'),
              ('latitude', '38.631913'),
              ('longitude', '-121.434879')]),
 OrderedDict([('street', '51 OMAHA CT'),
              ('city', 'SACRAMENTO'),
              ('zip', '95823'),
              ('state', 'CA'),
              ('beds', '3'),
              ('baths', '1'),
              ('sq__ft', '1167'),
              ('type', 'Residential'),
              ('sale_date', 'Wed May 21 00:00:00 EDT 2008'),
              ('price', '68212'),
              ('latitude', '38.478902'),
              ('longitude', '-121.431028')]),
 OrderedDict([('street', '2796 BRANCH ST'),
              ('city', 'SACRAMENTO'),
      

In [3]:
len(mpg)

985

In [4]:
mpg[0].keys()ea

odict_keys(['street', 'city', 'zip', 'state', 'beds', 'baths', 'sq__ft', 'type', 'sale_date', 'price', 'latitude', 'longitude'])

In [16]:
s = 0;
for d in mpg:
       s = s + float(d['beds'])
        
print(s/len(mpg))        


2.9116751269035532


In [8]:
sum(float(d['beds']) for d in mpg)/len(mpg)

2.91

In [10]:
import csv

%precision 2
with open ('mpg.csv') as csvfile:
     mpg=list(csv.DictReader(csvfile))
        
mpg[1:4]

[OrderedDict([('street', '51 OMAHA CT'),
              ('city', 'SACRAMENTO'),
              ('zip', '95823'),
              ('state', 'CA'),
              ('beds', '3'),
              ('baths', '1'),
              ('sq__ft', '1167'),
              ('type', 'Residential'),
              ('sale_date', 'Wed May 21 00:00:00 EDT 2008'),
              ('price', '68212'),
              ('latitude', '38.478902'),
              ('longitude', '-121.431028')]),
 OrderedDict([('street', '2796 BRANCH ST'),
              ('city', 'SACRAMENTO'),
              ('zip', '95815'),
              ('state', 'CA'),
              ('beds', '2'),
              ('baths', '1'),
              ('sq__ft', '796'),
              ('type', 'Residential'),
              ('sale_date', 'Wed May 21 00:00:00 EDT 2008'),
              ('price', '68880'),
              ('latitude', '38.618305'),
              ('longitude', '-121.443839')]),
 OrderedDict([('street', '2805 JANETTE WAY'),
              ('city', 'SACRAMENTO'),
  

In [12]:
CtyMpgByCyl = []

for c in street: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['street'] == c: # if the cylinder level type matches,
            summpg += float(d['city']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

NameError: name 'street' is not defined

In [13]:
streets = set(d['street'] for d in mpg)
streets

{'1 KENNELFORD CIR',
 '10 SEA FOAM CT',
 '100 CHELSEA CT',
 '100 CRYSTALWOOD CIR',
 '100 CRYSTALWOOD WAY',
 '100 REBECCA WAY',
 '100 TOURMALINE CIR',
 '10001 WOODCREEK OAKS BLVD Unit 1415',
 '10001 WOODCREEK OAKS BLVD Unit 815',
 '1001 RIO NORTE WAY',
 '1005 MORENO WAY',
 '10062 LINCOLN VILLAGE DR',
 '10085 ATKINS DR',
 '10104 ANNIE ST',
 '10105 MONTE VALLO CT',
 '10112 LAMBEAU CT',
 '10133 NEBBIOLO CT',
 '10158 CRAWFORD WAY',
 '1016 CONGRESS AVE',
 '10165 LOFTON WAY',
 '10245 LOS PALOS DR',
 '10254 JULIANA WAY',
 '1028 FALLON PLACE CT',
 '1032 SOUZA DR',
 '1033 PARK STREAM DR',
 '1035 MILLET WAY',
 '10372 VIA CINTA CT',
 '104 CATLIN CT',
 '1042 STARBROOK DR',
 '1044 GALSTON DR',
 '1050 FOXHALL WAY',
 '10542 SILVERWOOD WAY',
 '106 FARHAM DR',
 '10629 BASIE WAY',
 '1069 ACACIA AVE',
 '107 JARVIS CIR',
 '108 CRYSTALWOOD WAY',
 '1080 RIO NORTE WAY',
 '1092 MAUGHAM CT',
 '10949 SCOTSMAN WAY',
 '11 E ST',
 '110 COPPER LEAF WAY',
 '1102 CHESLEY LN',
 '1103 COMMONS DR',
 '1104 HILLSDALE LN',


CtyMpgByCyl = []

for c in streets: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['street'] == c: # if the cylinder level type matches,
            summpg += string(d['city']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

# import date and time


In [17]:
import datetime as dt
import time as tm

In [18]:
tm.time()

1590652143.72

In [21]:
dtnow = dt.datetime.fromtimestamp(tm.time())

In [22]:
dtnow

datetime.datetime(2020, 5, 28, 13, 20, 42, 953393)

In [23]:
dtnow.year

2020

In [24]:
dtnow.month

5

In [25]:
dtnow.date

<function datetime.date>

In [26]:
dtnow.datetime

AttributeError: 'datetime.datetime' object has no attribute 'datetime'

In [27]:
dtnow.day


28

In [28]:
dtnow.hour,dtnow.minute,dtnow.second

(13, 20, 42)

In [29]:
delta = dt.timedelta(100)

In [30]:
delta

datetime.timedelta(100)

In [31]:
today =  dt.date.today()

In [32]:
today-delta

datetime.date(2020, 2, 18)

In [33]:
today > today-delta

True

In [3]:
def even_or_odd(num):
    if num%2==0:
        return "The number {} is even".format(num)
    else:
        return "The number {} is odd".format(num)

In [5]:
even_or_odd(24)

'The number 24 is even'

In [8]:
lst=[1,2,3,4,5,6,7,8,9]

In [9]:
list(map(even_or_odd,lst))

['The number 1 is odd',
 'The number 2 is even',
 'The number 3 is odd',
 'The number 4 is even',
 'The number 5 is odd',
 'The number 6 is even',
 'The number 7 is odd',
 'The number 8 is even',
 'The number 9 is odd']

In [10]:
class computer:
    def config(self):
        print("i5,16gb,1tb")
        
        
comp1 = computer()


In [11]:
computer.config(comp1)

i5,16gb,1tb


In [14]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables = [i*j for i in range(10) for j in range(10)]
times_tables

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 0,
 4,
 8,
 12,
 16,
 20,
 24,
 28,
 32,
 36,
 0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 0,
 6,
 12,
 18,
 24,
 30,
 36,
 42,
 48,
 54,
 0,
 7,
 14,
 21,
 28,
 35,
 42,
 49,
 56,
 63,
 0,
 8,
 16,
 24,
 32,
 40,
 48,
 56,
 64,
 72,
 0,
 9,
 18,
 27,
 36,
 45,
 54,
 63,
 72,
 81]

In [16]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]
answer[:50]

['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09',
 'aa10',
 'aa11',
 'aa12',
 'aa13',
 'aa14',
 'aa15',
 'aa16',
 'aa17',
 'aa18',
 'aa19',
 'aa20',
 'aa21',
 'aa22',
 'aa23',
 'aa24',
 'aa25',
 'aa26',
 'aa27',
 'aa28',
 'aa29',
 'aa30',
 'aa31',
 'aa32',
 'aa33',
 'aa34',
 'aa35',
 'aa36',
 'aa37',
 'aa38',
 'aa39',
 'aa40',
 'aa41',
 'aa42',
 'aa43',
 'aa44',
 'aa45',
 'aa46',
 'aa47',
 'aa48',
 'aa49']

# Numpy


In [17]:
import numpy as np

# Creating numpy as arrays

In [18]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [19]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [21]:
z = np.array([[1,2,3],[4,5,6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
z.shape()

TypeError: 'tuple' object is not callable

In [23]:
z.shape


(2, 3)

In [26]:
n = np.arange(0,16,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [31]:
n = n.reshape(4,2)
n

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [33]:
o = np.linspace(0,5,10)
o

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [34]:
o.resize(5,2)
o

array([[0.        , 0.55555556],
       [1.11111111, 1.66666667],
       [2.22222222, 2.77777778],
       [3.33333333, 3.88888889],
       [4.44444444, 5.        ]])

In [35]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:

np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [46]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [48]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [49]:
p = np.ones([3,2],int)
p

array([[1, 1],
       [1, 1],
       [1, 1]])

In [51]:
np.vstack([p,2*p])

array([[1, 1],
       [1, 1],
       [1, 1],
       [2, 2],
       [2, 2],
       [2, 2]])

In [52]:
np.hstack([p,2*p])

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [1, 1, 2, 2]])


# Operations

In [53]:
x+y

array([5, 7, 9])

In [54]:
x * y

array([ 4, 10, 18])

In [55]:
x**2

array([1, 4, 9])

In [56]:
x.dot(y)

32

In [57]:
z =  np.array([y,y**2])

In [58]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [59]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [60]:
z.t.shape

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [61]:
z.T.shape

(3, 2)

In [62]:
a = np.array([1,2,3,-5,-6])

In [63]:
a.sum()

-5

In [64]:
a.max()

3

In [65]:
a.min()

-6

In [66]:
a.mean()

-1.0

In [67]:
a.std()

3.7416573867739413

In [68]:
a.argmax()

2

In [69]:
a.argmin()

4

# Indexing and slicing

In [70]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [71]:
s[0],s[4],s[1:4]

(0, 16, array([1, 4, 9]))

In [72]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [74]:
r = np.arange(36)
r.resize([6,6])
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [75]:
r[2,2]

14

In [76]:
r[3,3:6]

array([21, 22, 23])

In [77]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [80]:
r[-1,::2]

array([30, 32, 34])

In [81]:
r[r>30]

array([31, 32, 33, 34, 35])

In [82]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [114]:
r.reshape(36)[::7]
r


array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [85]:
r2[:]=0

In [86]:
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [87]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [92]:
r_copy = r.copy()
r_copy[:,0]=0
print(r_copy)
print(r)

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [ 0 19 20 21 22 23]
 [ 0 25 26 27 28 29]
 [ 0 30 30 30 30 30]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating over arrays

In [94]:
test = np.random.randint(0,10,(4,3))
test

array([[8, 4, 0],
       [1, 9, 5],
       [5, 9, 1],
       [8, 3, 7]])

In [97]:
for i in range (len(test)):
          print(test[i])

[8 4 0]
[1 9 5]
[5 9 1]
[8 3 7]


In [99]:
for i,row  in enumerate (test):
    print('row',i,'is',row)

row 0 is [8 4 0]
row 1 is [1 9 5]
row 2 is [5 9 1]
row 3 is [8 3 7]


In [100]:
test2 = test**2

In [101]:
test2

array([[64, 16,  0],
       [ 1, 81, 25],
       [25, 81,  1],
       [64,  9, 49]])

In [102]:
for i,j in zip(test,test2):
    print(i,'+',j,'=',i+j)
     

[8 4 0] + [64 16  0] = [72 20  0]
[1 9 5] + [ 1 81 25] = [ 2 90 30]
[5 9 1] + [25 81  1] = [30 90  2]
[8 3 7] + [64  9 49] = [72 12 56]


In [103]:
type(lamda x:x+1)

SyntaxError: invalid syntax (<ipython-input-103-1340b2977d75>, line 1)

In [104]:
x=[1,2,3]
type(lamda x:x+1)

SyntaxError: invalid syntax (<ipython-input-104-dda8fe96cd17>, line 2)

In [105]:
type(lamda)

NameError: name 'lamda' is not defined

In [3]:
import numpy as np
r= np.arange(36)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [4]:
r = r.reshape(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [5]:
r[2:4,2:4]


array([[14, 15],
       [20, 21]])